
name: 01d hola mundo dos

on:
  workflow_dispatch:
  push:
  
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola victor3
      run: echo "Hello Mundo borre el issue y guarde este"
