
name: disparo issue

on:
  workflow_dispatch:
  issues:
    types: [opened]
  
  
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: isuue
      run: echo "al crear un issue"





