name: 02 issue

on:
  push:
  issues:
    types:
        opened

  
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola victor hugo
      run: echo "Hello Mundo desde visual estudio"

